### ISSUE TITLE
def self.newは必要ない

### ISSUE THREAD

**Issue by shokai** [masui/Gyazz#131]
def initializeだけでいいと思うのですが
- https://github.com/masui/Gyazz/blob/master/models/page.rb#L10-L32
- https://github.com/masui/Gyazz/blob/master/models/wiki.rb#L8-L23

cacheが関係しているのでしょうか？

**Comment by zakuni** [comment]
#135 で解決済みです

**Comment by shokai** [comment]
![LGTM](http://www.lgtm.in/p/TDO1)
