### ISSUE TITLE
ファイルアップロード時にプログレスを表示したい

### ISSUE THREAD

**Issue by shokai** [masui/Gyazz#140]
プログレス（バー？）じゃなくても、今アップロード中なのかなんなのか表示したい（せめてドラッグアンドドロップができているのか程度でも）
何もフィードバックが無いので心臓が悪い

**Comment by masui** [comment]
window.open()するようにしますか

**Comment by shokai** [comment]
![タイトルバー](http://gyazo.com/5fe25594935ef4be42b3deee795b2f42.png)
このタイトルバーの背景とか使ってなんかできそうな気がします
