### ISSUE TITLE
コマンドキーを押した時のtriggerをkeydownではなくkeyupにしてほしい

### ISSUE THREAD

**Issue by geta6** [masui/Gyazz#24]

**Comment by shokai** [comment]
なんで？

**Comment by geta6** [comment]
例えばコピー(⌘C)しようとした時、keydownで検索ボックスにフォーカスが奪われるので、書かれている文章をコピーできない。keyupであればコピーした後にフォーカスが奪われるのでコピーはできる。

**Comment by masui** [comment]
ナルホド

**Comment by masui** [comment]
#27 によりコピー問題は解決してるみたいなので一応クローズします

**Comment by shokai** [comment]
解決してます。
