### ISSUE TITLE
modelを作るためのリファクタリング

### ISSUE THREAD

**Issue by shokai** [masui/Gyazz#35]
# `lib/*.rb`内のロジックにSDBMの操作が含まれているので、modelに切り出すべきか
1. それぞれが勝手にSDBMを開いているのが悪い、modelに集約すべき
2. controllerから呼ばれてるライブラリがerbでHTMLをレンダリングして文字列として返しているのをなんとかした方が良いかもしれない。controllerがviewの機能を持っている。
3. 認証しているかどうかをライブラリやviewやcontrollerがそれぞれ勝手にcookie見たりcheck_auth(name)という関数使ったりして調べているのもおかしい

model作るより先に、認証状態を取得するヘルパークラスから書くべきかもしれない
# `lib/*.rb`のコードを読んでみた

lib/の中身のmodelにできる部分はmodels/に移動したい
## 各ファイルの行数

```
     242 lib/search.rb
     230 lib/writedata.rb
     147 lib/auth.rb
     126 lib/pair.rb
     108 lib/related.rb
      84 lib/history.rb
      78 lib/keyword.rb
      76 lib/contenttype.rb
      73 lib/png.rb
      57 lib/rss.rb
      54 lib/page.rb
      53 lib/lib.rb
      32 lib/readdata.rb
      20 lib/access.rb
      19 lib/edit.rb
       9 lib/config_template.rb
       9 lib/attr.rb
```
### lib/search.rb
- wiki内のページ一覧を返すtitles関数がある
- wiki内のページを検索するsearch関数があるが、なぜか関数内でerbレンダリングしているのでcontrollerともども修正必要
### lib/writedata.rb
- writedataと__writedataという関数がある
- writedataは書き込み、__writedataは無条件書き込みらしい
- __writedataにはバックアップせずに書き込むオプションがある（第二引数）
- 第一引数が巨大な配列で、`[wiki名, ページ名, 以後ページの行データ]`となっている
- writedataは`post '__write'`から呼ばれる、旧式の書き込みらしい
- **writedataは`post '__write**'`から呼ばれる
- writedataは`"conflict"`か`"noconflict"`という文字列を返す。これをresponse bodyとして返すことにより、jsは書き込み衝突を検出している
- __writedataはなぜかリダイレクト先のpathを返すので、controllerからsinatraのredirect関数に渡される
### lib/auth.rb
- protected!, password_required?, password_authorized?, auth_page_exists?, auth_cookie, cookie_authorized? 関数を持っている
- 全部呼び出し元がcontrollerなので、helperに移動するべき
- auth_cookie関数はresponse.set_cookieにセットされるが、cookieがwiki名だけで生成される上、全ユーザー同じcookieなので公開されているソースを見れば誰でも認証つきページにログインできる脆弱性がある
### lib/pair.rb
- class Pairが定義されている
- 最古のKVSであるSDBMを、KVSではなく要素数2の配列の配列として扱うためのクラス
- `Gyazz.topdir/wiki名/pair`に保存される
  -関連検索に使っている。`[ページ名, リンク先]`で保存する
- `[[ページ名,リンク先], [ページ名,リンク先], [ページ名,リンク先]...]`のようになる
- Gyazz::Pairに移動し、これを直接使わずGyazz::Pageモデルから扱うようにするべき
- ページ内にどのページヘのリンクがあるか管理すればいいのだから、`Gyazz::Page.new('ページ名').relates`で取得するとか
### lib/related.rb
- pairを使った関連検索の関数がある
- _weight(name,title) で重み付けして related(name,title) で重要な順に返す
- related_html(name,title)がviewのerbから直接呼ばれているがescapeされていないのでページ名がそのままHTMLに出力される
  <img src="http://gyazo.com/51014b3af08d65d1c9f9c6701ece4d3a.gif"> 
- #56 で報告、 #57 で修正した
- related_htmlの呼び出し元が、controller->related.erb->related_html()->icon.erbとtexticon.erb となっていてマジでヤバイ
### lib/history.rb
- 履歴の視覚化関係の関数がある。ページ履歴を遡る機能には使われていない？
- history_json(name, title)はto_json使った方がいい
- history_png(name, title)はページの編集履歴をしましまのpng画像にして返す
- 全部Gyazz::Pageモデルに移動させる
- `Gyazz::Page.new('ページ名').histories`, `Gyazz::Page.new('ページ名').history_png`とか
### lib/keyword.rb
- `String#keywords`を定義している
- string.rbにしたほうがいいような
- testが下の方に書かれているので、tests/に移動させる
### lib/contenttype.rb
- `get "/upload/:filename"`から呼ばれている、つまりアップロードされたファイルを配信する時に使われる
- そもそも静的ファイル配信にsinatraでFile.readして返さないほうがいい
- とりあえず`Gyazz::ContentType`に移動させる
### lib/png.rb
- zlibでPNG画像を生成するライブラリ
- ようやくライブラリらしいライブラリがでてきた
- これはこのままでもいいかも
### lib/rss.rb
- rss(name)という関数がある
- wiki名を与えるとrssを生成する
- パスワードが必要なwikiの場合、本文は空にする（`password_required?`関数を使っている）
- `Gyazz::Wiki.new('wiki名').rss`とかにしたほうがいい
### lib/page.rb
- page(wiki名, ページ名, 認証確認フラグ) という関数1つがある
- `get '/__random'`や`get '/wiki名/ページ名'`で使われる重要な関数
- SDBMを開いてページ内容を読み取り、認証を確認して履歴をバックアップ保存しerbでHTMLを返す、色々詰め込みすぎ
- readdata()と役割が重複しているが、内部で`readdata`を使っているわけではない
### lib/lib.rb
- topdirとかbackupdirとかがある
- Gyazz.topdirとかGyazz.backupdirとかに直す（直した）
### lib/readdata.rb
- readdata(wiki名, ページ名, バージョン)という関数だけがある
- ページのデータを返す。lib/page.rbからは使われていない。
- バージョン指定された時になんかやってるけど全然理解できない
### lib/access.rb
- access(wiki名, ページ名)
  - アクセス履歴
  - jsonで返る
- modify(wiki名, ページ名)
  - 変更履歴
  - jsonで返る
- どちらもPage modelが持つべき
- どちらもjsonで返さないべき。データ構造で返して、json化するのはcontrollerの仕事
### lib/edit.rb
- edit(wiki名, ページ名, バージョン)
- `get '/:name/*/__edit'`と`get '/:name/*/__edit/:version'`から使われる
- 編集をする関数ではなく、編集画面のHTMLを生成するための関数（名前がおかしい）
- erb :editを返している、良くない
- 異なる日付入りのコメントアウトが大量にある
- 書き込み可能認証してるかどうかも判定している
- 書き込み可能認証しているかをviewに伝えるんじゃなくて、認証しているかでviewを切り替えるか問答無用でredirectすればいいだけだと思う
### lib/config_template.rb
- 設定ファイルのテンプレート
- できればGyazz::FILEROOTとかGyazz::DEFAULTPAGEとかになってほしい
### lib/attr.rb
- attr(wiki名)
- `get "/:name/.settings"`から使われている
- ライブラリなのにerbでHTMLをレンダリングして返していておかしい

**Comment by shokai** [comment]
# SDBMやファイルを直接開いているコード

```
% git grep "Dir\|File\|open\|sdbm\|SDBM" | ruby -lane 'puts $_.split(":")[0]' | sort | uniq -c | sort -nr
```

このへんが怪しいのでmodelにまとめられる所はまとめます

```
  27 lib/writedata.rb
  24 lib/search.rb
  20 gyazz.rb
   7 lib/related.rb
   7 lib/page.rb
   4 lib/rss.rb
   4 lib/auth.rb
   4 lib/access.rb
   3 public/javascripts/jQuery.kill_referrer.js
   3 lib/tmpshare.rb
   3 lib/png.rb
   3 lib/pair.rb
   2 public/javascripts/jquery.js
   2 lib/readdata.rb
   2 lib/lib.rb
   1 tests/run_suite.rb
   1 tests/rack_test.rb
   1 public/javascripts/gyazz.js
   1 lib/uploaded.rb
   1 lib/history.rb
   1 lib/edit.rb
   1 lib/attr.rb
   1 config.ru
```

**Comment by shokai** [comment]
`lib/tmpshare.rb` はcontrollerなのでlibから移動させる

**Comment by shokai** [comment]
重要そうな関数1つだけ書いてある`edit.rb`と`readdata.rb`が気になる
これもどこかに移動させる

**Comment by masui** [comment]
writedata()はreaddata()の反対みたいな仕様にしました

**Comment by shokai** [comment]
それぞれが勝手にSDBMを開いているのが悪い、modelに集約すべき

そう最初は思っていました。

調べた結果、先にcontrollerから呼ばれてるライブラリがerbでHTMLをレンダリングして返しているのをなんとかした方が良いかもしれない。
あと認証しているかどうかをライブラリやviewやcontrollerがそれぞれ勝手にcookie見たりcheck_auth(name)という関数つかったりして調べているのもおかしい。

ようするにどこから手をつけたらいいのかわからないレベル・・・

**Comment by masui** [comment]
長年場当たり的に機能拡張して酷いことになっててすみません...
とはいえゼロから再実装も面倒臭いですが、どうしましょう?

**Comment by masui** [comment]
related_html 関連は #53 みたいに直したいと思いますが如何?

**Comment by masui** [comment]
完全に書き直しました
