### ISSUE TITLE
アイコンの逆リンクをやめる

### ISSUE THREAD

**Issue by masui** [masui/Gyazz#43]
[[shokai.icon]]のようにアイコンで画像を登録したとき、shokaiページからのリンクを作成しない方が良い気がする

**Comment by masui** [comment]
[[*.icon]]にはリンクを作成しないことにした
@b52d12e

**Comment by shokai** [comment]
@b52d12eed6dff649dec11dee4ce67b36851f322c ですね

**Comment by masui** [comment]
はい。書き方忘れてました。
