### ISSUE TITLE
編集中の行が古い状態にもどるバグ

### ISSUE THREAD

**Issue by shokai** [masui/Gyazz#44]
編集中の行が一定時間ごとに元の行に巻き戻るバグが発生しています。

**Comment by masui** [comment]
writedata()が遅くて失敗してるためかもしれません。
とりあえず戻しましたが、サーバ処理が遅いとき問題が起こるバグがあるのかも...

**Comment by shokai** [comment]
ちなみに今は発生してないです

**Comment by masui** [comment]
リファクタリング後また発生してるような

**Comment by masui** [comment]
発生してますね... 早く対策しないと

**Comment by masui** [comment]
過去ログは残ってるので書き込み失敗してるわけじゃなさそう
コンフリクトと解釈して古いデータに自分で戻してるのではないか
コンフリクト判定と修正のロジックをなんとかする必要あり

**Comment by masui** [comment]
@6687427 で直ったかもしれない

**Comment by masui** [comment]
サーバの問題とFirefoxの問題と複合してるようで困っている。
Chromeだと問題が出なくなった気がするのだが

**Comment by masui** [comment]
IMEが日本語モードになってるとき $('input').val() を操作するとおかしなことになる > Firefox
操作する前後で blur() / focus() すれば多少マシになるぽい

**Comment by masui** [comment]
行編集中にキー入力したときサーバと通信するのを一切廃止
クリックしたときまたは別の行に移ったときはじめて通信することにした。
その方が全く都合が良いようだ。
