### ISSUE TITLE
認証用cookieが推測できてしまう脆弱性を直す

### ISSUE THREAD

**Issue by shokai** [masui/Gyazz#64]
`lib/auth.rb`の`auth_cookie`関数の返り値がresponse.set_cookieにセットされているが、cookieがwiki名だけで生成される上、全ユーザー同じcookieなので公開されているソースを見れば誰でも認証つきページにログインできる脆弱性がある

**Comment by masui** [comment]
確かにソース見れば作成できるような。どうやるのが定番なのかな?

**Comment by shokai** [comment]
よく考えると全員に同じcookieなのは別に良いと思います、が、cookieが推測できてしまうのはまずいです。

アルゴリズムが公開されていてもcookieが推測できないようにすればいいだけなので、環境変数やconfig.rbにsaltを指定すれば良いと思います

``` ruby
def create_cookie
  seed = "#{ENV["AUTH_SALT"]}_#{wiki_name}"
  return Digest::MD5.hexdigest(seed)
end
```

とか。これならsaltがわからなければcookieがわからないです。

**Comment by masui** [comment]
salt足しました
