### ISSUE TITLE
1行削除がやりにくい

### ISSUE THREAD

**Issue by masui** [masui/Gyazz#70]
Ctrl-Kで行を消したら次の行に移動したいかも

**Comment by masui** [comment]
Ctrl-K連打で次の行に移動すればいい (Emacsと同じ挙動)

**Comment by shokai** [comment]
そうですね。次の行にカーソル移動してしまえばctrl+kで消した行は空行削除で消滅しますね

**Comment by shokai** [comment]
これやってみます
