### ISSUE TITLE
編集モードの時、保存すると中身がhtmlに書き換わるバグ

### ISSUE THREAD

**Issue by TakumiBaba** [masui/Gyazz#81]
編集モードでページを編集して、フォーカスを外すと保存されるが、たまに以下の画像のように、中身がhtmlに書き換えられ、保存に失敗する。
4,5回に1回発生しているが、発生条件などはわからない。

![編集モードの時、たまにテキストエリアがhtmlに書き換えられ、保存に失敗する](http://gyazo.com/5ca75a15493146a58a128957026fccdd.png)

**Comment by masui** [comment]
サーバからのデータ取得に失敗してJSON受け取るかわりにHTMLを受け取ってる場合があるような?

**Comment by masui** [comment]
4-5回に一回ということは無いですがタマに遭遇しますね。
スマホだと通信が遅いからかも。
Ajaxあたりで何らかの問題があるのかもしれません。

**Comment by masui** [comment]
edit.js の getdata() からの呼び出しに問題があったようです。
書き込みコンフリクトが置きたときテキストを再読み出ししているのですが
そこで存在しないAPIを叩いていました...
修正したのでとりあえずクローズします。
@4aeae5b
