### ISSUE TITLE
"memo" コマンド追加

### ISSUE THREAD

**Issue by masui** [masui/Gyazz#91]
```
% memo
```

とすると日付をタイトルとしたGyazzページが開くというもの

**Comment by shokai** [comment]
これってこのリポジトリに入れるんですか？
入れるとしたら、pathが通らない（通しにくい場所にある）わけだからgemの依存とかなるべくないように実装しなければならない。

入れないなら、多分gyazz gemに同梱するのがいいと思います。

**Comment by shokai** [comment]
closeしていいと思います

**Comment by masui** [comment]
closeします
